// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-A19iPpQaglfIiPAUPh3nR_39kd3c8Ms',
    appId: '1:794066304083:web:5fa9417918443ba4e5daa6',
    messagingSenderId: '794066304083',
    projectId: 'briz-59ee3',
    authDomain: 'briz-59ee3.firebaseapp.com',
    storageBucket: 'briz-59ee3.appspot.com',
    measurementId: 'G-J1QL3D4Q9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgG_IPrU7mMShQ6f_y4HBO7hz6i20rD4',
    appId: '1:794066304083:android:82505904e0411d5ae5daa6',
    messagingSenderId: '794066304083',
    projectId: 'briz-59ee3',
    storageBucket: 'briz-59ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2HuC6Xi5An_cqx8MUL5qVjAPXwxMklh4',
    appId: '1:794066304083:ios:962b11979070f734e5daa6',
    messagingSenderId: '794066304083',
    projectId: 'briz-59ee3',
    storageBucket: 'briz-59ee3.appspot.com',
    iosClientId: '794066304083-16f9mf15jntc6nskjnc3htloefca6qfi.apps.googleusercontent.com',
    iosBundleId: 'com.briz.app',
  );
}
